### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by btsimonh** [zuhito/node-red-contrib-opencv#1]
Hi zuhito,

I'm sure you are following 
https://groups.google.com/forum/#!searchin/node-red/opencv$20anyone$20played%7Csort:date/node-red/GQeDS-CuK00/e0z25nU3CQAJ

We (bart & I?) would like to contribute to your node rather than produce a new one..... to produce a more generic node-set.  After all you have the good node name :).

Do you have specific plans?

best regards,

Simon

**Comment by bartbutenaers** [comment]
Hi zuhito,
 
Simon has been so kind to invite me here ;-)
If you have plans to build an opencv suite (motion detection, face recognition, ...), it would be great if I could collaborate with you guys in the future.

Kind regards,
Bart

**Comment by zuhito** [comment]
@btsimonh @bartbutenaers 
Really sorry, I overlooked your messages. Currently there's no plan to enhance the node. Of course, your contributions and suggestions are welcomed!
I invited you to this project and [npmjs](https://www.npmjs.com/package/node-red-contrib-opencv) because I already know that you're great contributors for Node-RED! :)

**Comment by btsimonh** [comment]
hi zuhito,
accepted :).
been kind of busy lately with work; but still wish to get a good node-red opencv integration going.
If you get a chance, please read and comment on:

https://github.com/btsimonh/node-red-contrib-ocv/wiki

it's a public wiki for trying to develop ideas around how best to make it work.
looking for some inspiration as to how we deal with queues of images, etc.....

best,
simon

**Comment by bartbutenaers** [comment]
Hello Zuhito,

Thanks for the invitation!  Have also accepted it.
Hopefully we find some time in the next months to cooperate on this. 
But it will be quite a challenge ...

Kind regards,
Bart

**Comment by zuhito** [comment]
Thank you for sharing it. I was amazed because it's very detail and looks useful.
I'm interested in series of node in node-red-contrib-opencv module. Currently there's one nodes in the module. I think that sort of nodes and their nodes property UI are important in terms of userbility. If OpenCV functions are well-organized, OpenCV nodes should inherits the structure of functions in opencv. It will be good for existing OpenCV users to understand in OpenCV nodes.
You can use this repository and npmjs for development and publishing of node-red-opencv because I know that you're great contributors for Node-RED community as I said before.
